// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXQbpJYHVAk57xYvvoYEpryidXOcbwvXo',
    appId: '1:679693264549:web:e819f3732cf88b1b490f4c',
    messagingSenderId: '679693264549',
    projectId: 'mentalhealthsupportapp-46bc1',
    authDomain: 'mentalhealthsupportapp-46bc1.firebaseapp.com',
    storageBucket: 'mentalhealthsupportapp-46bc1.firebasestorage.app',
    measurementId: 'G-6WNHPVZGCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJC__idNo7njTwQd3tgqB3sbJrNxxBFbI',
    appId: '1:679693264549:android:0365ca9af318af20490f4c',
    messagingSenderId: '679693264549',
    projectId: 'mentalhealthsupportapp-46bc1',
    storageBucket: 'mentalhealthsupportapp-46bc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp5No5gpU3jia8HvNs8tzuRmWpHrnHTIM',
    appId: '1:679693264549:ios:033c9f8a27e86b56490f4c',
    messagingSenderId: '679693264549',
    projectId: 'mentalhealthsupportapp-46bc1',
    storageBucket: 'mentalhealthsupportapp-46bc1.firebasestorage.app',
    iosBundleId: 'com.mentalhealthsupport.mentalHealthSupportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp5No5gpU3jia8HvNs8tzuRmWpHrnHTIM',
    appId: '1:679693264549:ios:033c9f8a27e86b56490f4c',
    messagingSenderId: '679693264549',
    projectId: 'mentalhealthsupportapp-46bc1',
    storageBucket: 'mentalhealthsupportapp-46bc1.firebasestorage.app',
    iosBundleId: 'com.mentalhealthsupport.mentalHealthSupportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXQbpJYHVAk57xYvvoYEpryidXOcbwvXo',
    appId: '1:679693264549:web:e0a5af32792ef79e490f4c',
    messagingSenderId: '679693264549',
    projectId: 'mentalhealthsupportapp-46bc1',
    authDomain: 'mentalhealthsupportapp-46bc1.firebaseapp.com',
    storageBucket: 'mentalhealthsupportapp-46bc1.firebasestorage.app',
    measurementId: 'G-JLQP0V4Q72',
  );
}
